---
# タスクの実行に必要な変数が定義されているか確認する
- name: Check if remote_filepath_job_result is defined
  ansible.builtin.assert:
    that:
      - remote_filepath_job_result is defined and remote_filepath_job_result != ""
    fail_msg: "Required variable 'remote_filepath_job_result' is not defined or is empty. Please set it in the playbook or inventory."

# リモートサーバー上からジョブ結果ファイルを取得
- name: Get job result content from remote file
  ansible.builtin.fetch:
    src: "{{ remote_filepath_job_result }}"
    dest: "{{ local_tmp_path | default('/tmp') }}/{{ remote_filepath_job_result | basename }}"
    flat: yes
  register: job_result_file

# ServiceNOWのテーブルにアップロードする情報をファイルから取得する
- name: Gather job result variables from specified file upload to ServiceNow Table
  ansible.builtin.include_vars:
    file: "{{ job_result_file.dest }}"
  delegate_to: localhost
  when:
    - job_result_file is defined
    - not job_result_file.failed
