---
- name: Set upload api rest_api_endpoint
  ansible.builtin.set_fact:
    upload_api_endpoint: "{{ servicenow_instance }}/api/now/attachment/file?table_name={{ target_table_name }}&table_sys_id={{ record_sys_id }}"
    upload_file_body: "{{ lookup('file', upload_log_filepath) }}"
  when:
    - record_sys_id is defined
    - upload_log_filepath is defined

- name: Upload log files to ServiceNow
  ansible.builtin.uri:
    url: "{{ upload_api_endpoint }}&file_name={{ upload_log_filepath | basename }}"
    headers:
      Content-Type: "text/plain"
      Accept: "application/json"
    method: "POST"
    user: "{{ servicenow_user }}"
    password: "{{ servicenow_password }}"
    body: "{{ upload_file_body }}"
    status_code: 201
  when: 
    - upload_file_body is defined
    - upload_api_endpoint is defined
  register: log_upload_response

- name: Set log_file_sys_id from uploaded result
  ansible.builtin.set_fact:
    log_file_sys_id: "{{ log_upload_response.json.result.sys_id }}"
  when:
    - log_upload_response is defined
    - log_upload_response.json is defined and 'result' in log_upload_response.json
