---
# タスクの実行に必要な変数が定義されているか確認
# record_sys_id: ServiceNowのレコードのsys_idを指定, 前のタスクで設定されることを想定
# VAR_upload_log_filepath: アップロードするログファイルのパスを指定, ユーザーにより設定される
- name: Check required variables
  ansible.builtin.assert:
    that:
      - record_sys_id is defined
      - VAR_upload_log_filepath is defined
      - VAR_servicenow_instance_url is defined
      - VAR_servicenow_target_table_name is defined
      - VAR_servicenow_user is defined
      - VAR_servicenow_password is defined
    fail_msg: "One or more required variables (VAR_record_sys_id, VAR_upload_log_filepath, VAR_servicenow_instance_url, VAR_servicenow_target_table_name, VAR_servicenow_user, VAR_servicenow_password) are not defined. Please set them in the playbook, inventory, or Vault."

# uriモジュールの実行に必要な一時変数を設定
# VAR_servicenow_instance_url: ServiceNowのインスタンスURLを指定, ユーザーにより設定される
# VAR_servicenow_target_table_name: ServiceNowのターゲットテーブル名を指定, ユーザーにより設定される
- name: Create Temporary Variable for uri module to upload log file
  ansible.builtin.set_fact:
    _upload_api_endpoint: "{{ VAR_servicenow_instance_url | trim('/') }}/api/now/attachment/file?table_name={{ VAR_servicenow_target_table_name }}&table_sys_id={{ record_sys_id }}"
    _upload_file_body: "{{ lookup('file', VAR_upload_log_filepath) }}"
    _upload_file_name: "{{ VAR_upload_log_filepath | basename }}"

# ServiceNowの指定されたテーブルにジョブ結果のログファイルをアップロード
# upload_file_name: アップロードするファイル名を指定, デフォルトではupload_log_filepathからbasenameを取得
- name: Upload log files to ServiceNow
  ansible.builtin.uri:
    url: "{{ _upload_api_endpoint }}&file_name={{ upload_file_name | default(_upload_file_name) }}"
    headers:
      Content-Type: "text/plain"
      Accept: "application/json"
    method: "POST"
    user: "{{ VAR_servicenow_user }}"
    password: "{{ VAR_servicenow_password }}"
    body: "{{ _upload_file_body }}"
    status_code: 201
    validate_certs: yes
  register: log_upload_response
  failed_when: log_upload_response.status != 201 or 'error' in log_upload_response.json | default({})

# 次のタスクで使用するため、レスポンスからアップロードしたログファイルのsys_idを設定
- name: Set log_file_sys_id from uploaded result
  ansible.builtin.set_fact:
    log_file_sys_id: "{{ log_upload_response.json.result.sys_id }}"
  when:
    - log_upload_response is defined
    # - log_upload_response.json is defined and 'result' in log_upload_response.json
    - ('result' in log_upload_response.json | default({}))
    - log_upload_response.json.result.sys_id is defined
