# tasks/main.yml
---
- import_tasks: 01_gather_job_result.yml
- import_tasks: 02_validation.yml
- import_tasks: 03_create_record_to_servicenow.yml
# ログファイルの指定がある場合のみ、次のタスクを実行
- import_tasks: 04_upload_log_file_to_created_record.yml
  when:
    - VAR_upload_log_filepath is defined
- import_tasks: 05_patch_record_with_log_file_sys_id.yml
  when:
    - VAR_upload_log_filepath is defined
