---
# uriモジュールの実行に必要な一時変数を設定
# servicenow_instance_url: ServiceNowのインスタンスURLを指定, ユーザーにより設定される
- name: Create Temporary Variable for uri module to delete record
  ansible.builtin.set_fact:
    _servicenow_api_endpoint: "{{ servicenow_instance_url }}/api/now/table/incident/{{ incident_sys_id }}"

- name: Delete Incident Record to ServiceNow
  ansible.builtin.uri:
    url: "{{ _servicenow_api_endpoint }}"
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
    method: "DELETE"
    user: "{{ servicenow_user }}"
    password: "{{ servicenow_password }}"
    status_code: 204
  register: response
