# tasks/main.yml
---
# record_actionが定義されているかの確認
- name: Check defined record_action
  ansible.builtin.fail:
    msg: "record_action is not defined. Please set the record_action variable to 'create', 'update', or 'delete'."
  when: record_action is not defined

# record_actionを小文字にして変数に設定
- name: Set record_action to lowercase
  ansible.builtin.set_fact:
    record_action: "{{ record_action | lower }}"

# record_actionが"create", "update", "delete"のいずれかであることを確認
- name: Validate record_action
  ansible.builtin.fail:
    msg: "record_action must be one of 'create', 'update', or 'delete'."
  when: record_action not in ['create', 'update', 'delete']

- import_tasks: 01_gather_incident_description.yml
- import_tasks: 02_validation.yml

# record_actionが"create"の場合の処理
- include_tasks: 03_create_record_to_servicenow.yml
  when: record_action == "create"

# record_actionが"update"の場合の処理
- include_tasks: 04_update_record_to_servicenow.yml
  when: record_action == "update"

# record_actionが"delete"の場合の処理
- include_tasks: 05_delete_record_to_servicenow.yml
  when: record_action == "delete"
