---
# vm-template-<テンプレート名>-credentials.yml
# このファイルはVMテンプレートの認証情報を定義します。
# 使用時は必ずansible-vaultで暗号化してください
vm_template_username: "your_vm_username"
vm_template_password: "your_vm_password"
vm_template_sudo_password: "your_vm_sudo_password"
