---
# vCenterサーバーの号機(最小値: 1, 最大値: 99)
vcenter_number: 1

# VM設定, 必要に応じてansible-vaultで暗号化してください
vm_name: 
vm_datacenter: 
vm_cluster: 
vm_folder: 
vm_notes: "Provisioned by Ansible"
# customization_specで使用するOSファミリー
# "RedHat" または "Windows" を指定します
vm_os_family: "RedHat"

# VMリソース設定
vm_cpu_cores: 
vm_memory_mb: 
vm_os_disk_size_gb: 
vm_os_disk_type: "thin"   # "thin" or "thick"
vm_os_disk_datastore: null

# VM電源状態
vm_power_state: "poweredon"  # "poweredOn", "poweredOff", "suspended"

# 初回OS設定用管理ネットワーク, このネットワークはDHCPでのIP取得を想定
vm_os_setting_network_portgroup: "VM Network"

# VMテンプレート設定, それぞれのOSに応じて設定
vm_template_name: 

# VMドメイン設定, 必要に応じてansible-vaultで暗号化してください
vm_domain: 

# --- CPU/メモリの詳細設定 ---
vm_cpu_reservation: null     # CPU予約（MHz）
vm_memory_reservation: null  # メモリ予約（MB）
vm_memory_limit: null        # メモリ制限（MB）
