# defaults/main.yml
---
# Role内で使用する変数のデフォルト値定義
servicenow_user: ""
servicenow_password: ""
servicenow_instance_url: "https://<instance_id>.service-now.com/"
servicenow_target_table_name: ""
remote_filepath_job_result: "/tmp/job_result.json"
remote_filepath_upload_log: "/var/log/exastro/exec.log"
local_tmp_path: "/tmp"
