---
# 本タスクの実行ではansible-vaultで暗号化されたファイルを読み込みます
# 実行時に--ask-vault-passまたは--vault-password-fileオプションが必要です

# vcenter_numberに応じてvCenterサーバーの認証情報を取得
- name: Load vCenter credentials
  ansible.builtin.include_vars:
    file: "vars/vcenter-{{ '%02d' | format(vcenter_number) }}-credentials.yml"

# テンプレート名からvars/vm-template-<template_name>-credentials.ymlを読み込む
- name: Load template credentials (vault encrypted)
  ansible.builtin.include_vars:
    file: "vars/vm-template-{{ vm_template_name }}-credentials.yml"
