---
# 指定されたVMの状態をチェックしてvm_infoに保存
- name: Gather VM info to check power state
  include_tasks: get-vm-info/get-id-folder-eth0-by-vm-name.yml

# VMが電源オンの状態でない場合はエラー出力して終了
- name: Fail if VM is not powered off
  ansible.builtin.fail:
    msg: "VM '{{ vm_name }}' must be powered off for this operation."
  when:
    - not ansible_check_mode
    - vm_power_state != 'poweredOff'

# 正常にVMの状態を取得できた場合はvalidation_okをtrueに設定
# チェックモードでは常にtrueに設定
- name: Set validation_ok to true
  ansible.builtin.set_fact:
    validation_ok: true
